### ISSUE TITLE
Image assets not being digested

### ISSUE THREAD

**Issue by SampsonCrowley** [cookiecutter-flask/cookiecutter-flask#994]
I used the exact command from the readme: `cookiecutter https://github.com/cookiecutter-flask/cookiecutter-flask.git`

```
cd app_name
pipenv install --dev
pipenv shell
npm install
npm start
```

I put an image into `assets/img/my.png` and tried to load it:
```html
<img rel="shortcut icon" href="{{ static_url_for('static', filename='build/img/my.png') }}">
```
I then expected the server to return the digested `static_url_for` (e.g. `/static/build/2430afhpsqt480y.png`), but instead just receive `<img rel="shortcut icon" href="/static/build/img/my.png">` despite the fact that this template doesn't even put the images into an `img` subfolder for `static/build`. All img assets return an invalid url, even though js and css assets work correctly. I have tried both with and without `img` prefix.

there is also never a `manifest.json` generated to check what went wrong

Project configuration:

|      Option                              |                                Values                                 |
|------------------------------------------|-----------------------------------------------------------------------|
| `use_pipenv`                             | <ul><li>- [X] `yes`</li><li>- [ ] `no`</li></ul>                      |
| `python_version`                         | <ul><li>- [X] `3.8`</li><li>- [ ] `3.7`</li><li>- [ ] `3.6`</li></ul> |
| `node_version`                           | <ul><li>- [X] `12`</li><li>- [ ] `10`</li></ul>                       |
| `use_heroku`                             | <ul><li>- [X] `yes`</li><li>- [ ] `no`</li></ul>                      |
| Are you using Docker to run the app?     | <ul><li>- [ ] `yes`</li><li>- [X] `no`</li></ul>                      |

**Comment by SampsonCrowley** [comment]
Also in windows, fyi

**Comment by SampsonCrowley** [comment]
It's also worth mentioning that I can see the image with the digested filename *in* the root of `static/build`, the `static_url_for` method just isn't returning the path to it

**Comment by jamescurtin** [comment]
Looks like there are two separate things happing here:

* There was a bug in the file loader configuration (resolved in https://github.com/cookiecutter-flask/cookiecutter-flask/pull/996) that prevented assets from being bundled correctly by webpack. Pulling in these changes should resolve the issue.
* The static file digest is created when the image is built (`docker-compose build flask-prod`) and the manifest and digested files are stored within the image. By default, the `docker-compose.yml` mounts the local file system into the container ([here](https://github.com/cookiecutter-flask/cookiecutter-flask/blob/17d4944121e8fcbad5aa08a6570358e4fde417e8/%7B%7Bcookiecutter.app_name%7D%7D/docker-compose.yml#L40)), which takes precedence. If you remove the volume mounts from `flask-prod` then inspect the HTML, you will see that Flask has templated in the hashed version of the file. It might make sense to update the docker compose file to not mount the local file system for the prod service--but need to think about that before making a change.

Does this address the issues you were seeing? If so, please feel free to close out the issue. Thanks for filing the bug!

**Comment by SampsonCrowley** [comment]
As noted in the big report template, not using docker, running on ubuntu WSL

I will see if the update config fixes the issue of incorrect urls

**Comment by jamescurtin** [comment]
Just put up https://github.com/cookiecutter-flask/cookiecutter-flask/pull/997 to add an additional command to the "running locally" section

**Comment by SampsonCrowley** [comment]
in a proper webpack environment running a production build should not be involved in running a dev server, and in fact can cause "stuck" assets, where your changes aren't shown because the server is serving the production build instead of the current assets

**Comment by SampsonCrowley** [comment]
and also irrelevant to the issue in that it still occurred after running build; as I mentioned the assets were compiled, they just weren't returned in the url helper

**Comment by SampsonCrowley** [comment]
The updated config seems to work, though running build first is still required
